# Generated by Django 2.2.28 on 2026-03-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
