# Generated by Django 2.2.28 on 2026-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20260321_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='guess_region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
