# Generated by Django 2.2.28 on 2026-03-21 20:56

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_guess_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.artwork_image_upload_path),
        ),
    ]
