# Generated by Django 2.2.28 on 2026-03-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20260321_2056'),
        ('game', '0004_adminprofile'),
    ]

    operations = [
    ]
